name: Continuous CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1


      # Install newman globally
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-slackreporter
         npm install -g newman-reporter-htmlextra


      # Make directory to upload test results 
      - name: Make Directory for Results
        run: mkdir -p testResults

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Run postman collection
      - name: Run Postman Collection 
        env:
          COLLECTION_URL: ${{ secrets.COLLECTION_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
        run: |
          newman run https://api.getpostman.com/collections/12405857-6fb53e6d-410c-4b9c-be3a-53f6edcad856?apikey=PMAK-616adf2705876300343d1794-0a587a6129952fc9fbfbc8ddb5137e77cc -x -r slackreporter,htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-title "Corinth API Test Report" --reporter-htmlextra-hideRequestBody "Create a user, Create a user Copy" --reporter-htmlextra-hideResponseBody "Create a user" --reporter-slackreporter-webhookurl https://hooks.slack.com/services/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 --reporter-slackreporter-token xoxb-35823106962-2609755933445-7ACJpjj0DXvzBLvH8oo5ZK1U --reporter-slackreporter-chanel 'delphi-corinth-test'


      # Upload the contents of Test Results directory to workspace
      - name: Output the run results
        uses: actions/upload-artifact@v2
        with:
         name: Corinth ${{steps.date.outputs.date}}
         path: testResults
